### ISSUE TITLE
Train custom dataset.

### ISSUE THREAD

**Issue by Wooks-git** [jhb86253817/PIPNet#10]
Hello, author thanks for sharing your code.

i want to training my custom dataset, but when i run train.py, i have an Error named 'ModuleNotFoundError: No module named 'PIPNet' '. so how can i get PIPNet module?

**Comment by jhb86253817** [comment]
> Hello, author thanks for sharing your code.
> 
> i want to training my custom dataset, but when i run train.py, i have an Error named 'ModuleNotFoundError: No module named 'PIPNet' '. so how can i get PIPNet module?

Hi, it seems it has nothing to do with the dataset. Have you changed the folder name 'PIPNet'? If so, please also line 31 in train.py and line 35 in test.py

**Comment by Wooks-git** [comment]
I solve my problem! Thank you author!
