### ISSUE TITLE
How to train on my own dataset?

### ISSUE THREAD

**Issue by sky-fly97** [jhb86253817/PIPNet#12]
Hello， I have a batch of expanded images and corresponding ldmk annotations. I want the model to be trained both on 300W and my own data at the same time. How should I do?

**Comment by jhb86253817** [comment]
Hi, could you give more details, e.g., what do you mean by expanded images? Larger than 256x256?

**Comment by jhb86253817** [comment]
Hi, could you give more details, e.g., what do you mean by expanded images? Larger than 256x256?

**Comment by sky-fly97** [comment]
> Hi, could you give more details, e.g., what do you mean by expanded images? Larger than 256x256?

Hi， thanks for your qucik reply， I'm going to use a batch of 256*256 face images generated by GAN to expand the 300W training set for training. I read the preprocess.py carefully. In fact, this should be a simple thing. Only need to add the expanded data in 300W and change a little code.
