### ISSUE TITLE
some question about curriculum training

### ISSUE THREAD

**Issue by OuYag** [jhb86253817/PIPNet#16]
Hello, it is very nice work! I have some question about  curriculum  training.
I have attention that the line 239-242 in train_gssl.py，that mean every loop in task_type_list you should build a new network model in the code ?  And I have no find current loop training loading last loop saved weight? 
this way can promise the model learning easy to hard?  
Looking forward to your reply.

**Comment by jhb86253817** [comment]
> 

Hi. Yes, when there is better estimate of pseudo labels, the model will be trained from scratch, otherwise the wrong pseudo labels from last iteration may harm the model. And this is not something new in our curriculum strategy, but a common practice of self-training. Hope I answered your question.

**Comment by OuYag** [comment]
Thank you for your reply. I have clearly understood this principle.
