### ISSUE TITLE
Only 19 of 21 landmarks in AFLW use? Why? Can not found settings in CPM.

### ISSUE THREAD

**Issue by DefTruth** [jhb86253817/PIPNet#17]
hi~ I have found that you only use 19 of 21 landmarks in AFLW, and point out that it's follow [CPW](https://arxiv.org/pdf/1602.00134.pdf). But, I can't found any information about AFLW setting in CPM's paper. Could you please release the detail indices of 19 landmarks you have used in you paper? 

I see the code in `train.py`:
```python
points_flip = [6, 5, 4, 3, 2, 1, 12, 11, 10, 9, 8, 7, 15, 14, 13, 18, 17, 16, 19]  # no 0 and 20
points_flip = (np.array(points_flip)-1).tolist()  # then from 0~18, total 19 points
```
so, it means that you have exclude 0 and 20 in AFLW ?

**Comment by jhb86253817** [comment]
Hi, in the paper, we did not refer to CPM, but this work: Zhu S, Li C, Loy CC, Tang X (2016) Unconstrained face alignment via cascaded compositional learning. In: CVPR. Please check again.

**Comment by DefTruth** [comment]
Thanks~ PIPNet seems can get good performance in my tests 👍👍👍

**Comment by jhb86253817** [comment]
Thank you for your interests~
