### ISSUE TITLE
How to get 98 facial keypoints model?

### ISSUE THREAD

**Issue by Tristan1419** [jhb86253817/PIPNet#18]
How can I get your pre-trained 98 key points model?
which is showed in run_demo.sh （r18）

**Comment by jhb86253817** [comment]
> How can I get your pre-trained 98 key points model? which is showed in run_demo.sh （r18）

Hi, you can download from this link: https://drive.google.com/drive/folders/1WruSmUzb2mqZnSiqWO8wRWZcttaxmNnZ
