### ISSUE TITLE
The predicted landmarks appear out of face box

### ISSUE THREAD

**Issue by Tom-DaLin** [jhb86253817/PIPNet#24]
In order to shorten the detection time of the face detect, I predict the face box of the current frame by using the landmark of the previous frame of the image. In some cases, the landmarks predicted by PIPNet predicted would appear outside my face box.

In the image below, the area in the red box is the image I entered into the network, and the green dot is the landmarks predicted by PIPNet. 

![image](https://user-images.githubusercontent.com/52828870/169187095-fbd93068-f10b-4f70-995d-806f6b45585b.png)

Some of these landmarks appear outside the box, does anyone know why?

**Comment by jhb86253817** [comment]
Hi, I think is actually normal to predict outside because the face is outside, and there is no restrict to prevent it being outside.

**Comment by Tom-DaLin** [comment]
I am a beginner, and thank you very much for your answer
