### ISSUE TITLE
relative import error

### ISSUE THREAD

**Issue by wwdok** [jhb86253817/PIPNet#26]
![image](https://user-images.githubusercontent.com/43233772/173002041-d8eb6a2c-f7a3-425f-a17c-7352c5abe4f5.png)

**Comment by jhb86253817** [comment]
Hi, have you run FaceBoxesV2/utils/mask.sh to build for nms?

**Comment by wwdok** [comment]
No...  Then i run FaceBoxesV2/utils/make.sh, but i find in WIndows, it can not recoginze python3, so i change it to python, continuely, it report an error:
![image](https://user-images.githubusercontent.com/43233772/177092414-fe8343d9-ecbf-4125-b302-f17097320f84.png)
so i comment out the extra compile args:
![image](https://user-images.githubusercontent.com/43233772/177093331-d44b788a-adc4-4b22-94bd-e795692f4ecf.png)

rebuild it, this time it seems successful:
![image](https://user-images.githubusercontent.com/43233772/177093448-e9f66dad-8fbb-406d-9fcc-da9db0cbddf1.png)
Then i rerun `python lib/demo.py experiments/WFLW/pip_32_16_60_r18_l2_l1_10_1_nb10.py images/1.jpg`, it report another error:
![image](https://user-images.githubusercontent.com/43233772/177093748-e492b7f3-5c76-4abe-8f8d-62d4052cc8ca.png)

**Comment by jhb86253817** [comment]
You may refer to the following issue:
https://github.com/jhb86253817/PIPNet/issues/15#issue-1121603944

**Comment by wwdok** [comment]
Great, i finnally get the result ! I think the key point is change the line 25 of cpu_nms.pyx to:
`cdef np.ndarray[np.int_t, ndim=1] order = scores.argsort()[::-1].astype('int32')`, because in build.py I uncommented the line 46 and commented the line 47, this give me warning when rebuild(before rerun `python build.py build_ext --inplace`, delete build folder and nms/cpu_nms.c and nms/cpu_nms.cp38-win_amd64.pyd):
![image](https://user-images.githubusercontent.com/43233772/177099400-172c7076-13df-42f1-bbc2-41e14086c19d.png)
But this does not impact the final result.
