### ISSUE TITLE
train_gssl.py problem

### ISSUE THREAD

**Issue by ly0303521** [jhb86253817/PIPNet#28]
Hello, when I use train_gssl.py,   "300W nme is inf", is this normal?
> 300W nme: inf 
COFW nme: 0.05221280819123009
WFLW nme: 0.08741295886838747

**Comment by jhb86253817** [comment]
Not normal. Since the norm is the denominator, you may check if it is normal. try printing the norm value of every test image

**Comment by ly0303521** [comment]
> Not normal. Since the norm is the denominator, you may check if it is normal. try printing the norm value of every test image

When it comes to side face, the point of 36 and 45 is very very close , so the norm is 0. Now when norm is 0, i didnt use it

**Comment by jhb86253817** [comment]
OK, it makes sense, although I didn't encounter this problem.
You may skip these for now, and check in details later.
