### ISSUE TITLE
How to detect abnormal landmark prediction?

### ISSUE THREAD

**Issue by John1231983** [jhb86253817/PIPNet#30]
For inference, we still have some image that have landmark prediction very bad which has wrong face shape (compare with regression method)? Could you suggest any way to filter the result ? Note that, I am using video as input and landmark score that we used may not good

**Comment by jhb86253817** [comment]
Two possible solutions:
(1) use confidence score. You can choose a threshold empirically, and filter the results that is below the threshold
(2) use temporal consistency. You can calculate the difference between two or more frames, and if it is larger than certain threshold, filter it.

You could also combine the two. I havn't tried these tricks yet, so don't know if they work well. You may need some explorations.
