### ISSUE TITLE
from .nms.cpu_nms import cpu_nms, cpu_soft_nms ModuleNotFoundError: No module named 'utils.nms.cpu_nms'

### ISSUE THREAD

**Issue by XinyingZheng** [jhb86253817/PIPNet#31]
from .nms.cpu_nms import cpu_nms, cpu_soft_nms ModuleNotFoundError: No module named 'utils.nms.cpu_nms'
I've run  make.sh, but still get this error

**Comment by jhb86253817** [comment]
> from .nms.cpu_nms import cpu_nms, cpu_soft_nms ModuleNotFoundError: No module named 'utils.nms.cpu_nms' I've run make.sh, but still get this error

Hi, this is a module taken from faster rcnn. You may search this error on google for a solution. It works fine for Ubuntu, but may cause problem under Windows.

**Comment by XinyingZheng** [comment]
Yes, it is indeed the environmental problem, I have solved it, your work is very good, thank you for your reply!
 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jhb86253817/PIPNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 晚上11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jhb86253817/PIPNet] from .nms.cpu_nms import cpu_nms, cpu_soft_nms ModuleNotFoundError: No module named 'utils.nms.cpu_nms' (Issue #31)





  
from .nms.cpu_nms import cpu_nms, cpu_soft_nms ModuleNotFoundError: No module named 'utils.nms.cpu_nms' I've run make.sh, but still get this error
  
Hi, this is a module taken from faster rcnn. You may search this error on google for a solution. It works fine for Ubuntu, but may cause problem under Windows.
