### ISSUE TITLE
How to get the credibility of the key points of the face？

### ISSUE THREAD

**Issue by z411500976** [jhb86253817/PIPNet#33]
Some parts of the face may be occluded. The key points should be predicted. Can you get the credibility value?

**Comment by jhb86253817** [comment]
Hi, the `max_cls` returned by function `forward_pip` is the confidence scores of predicted landmarks.

**Comment by z411500976** [comment]
Thank you for your answer, but some of the max_cls values ​​I obtained are greater than 1. What is the maximum confidence?
![QQ图片20221022194922](https://user-images.githubusercontent.com/24216715/197337732-e0f5363c-c18e-494f-a424-77f62f4679a9.png)

**Comment by jhb86253817** [comment]
The ground-truth for training the heatmap is 1, but with L2 loss. Thus, it is possible that the predicted value is slightly larger than 1. You may simply clamp these to one.

**Comment by z411500976** [comment]
Understood, thanks
