### ISSUE TITLE
Can the project be deployed on WINDOWS

### ISSUE THREAD

**Issue by Forgeter0** [jhb86253817/PIPNet#36]
Can the project be deployed on WINDOWS？

**Comment by jhb86253817** [comment]
Hi, I think it is possible since the project heavily relies on PyTorch. For the compiling of the NMS module of face detector, you may refer to this issue: https://github.com/jhb86253817/PIPNet/issues/15

**Comment by Forgeter0** [comment]
Problem solved, thank you very much for your reply！




---Original---
From: "Haibo ***@***.***&gt;
Date: Wed, Nov 16, 2022 12:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jhb86253817/PIPNet] Can the project be deployed on WINDOWS(Issue #36)




 
Hi, I think it is possible since the project heavily relies on PyTorch. For the compiling of the NMS module of face detector, you may refer to this issue: #15
