### ISSUE TITLE
Excuse me,How to get the data for this file,'meanface.txt'

### ISSUE THREAD

**Issue by Forgeter0** [jhb86253817/PIPNet#39]
My understanding is that this line of code is to get the index of the 10 coordinate points of the NMS. 
But where did this initial file（,'meanface.txt'） come from?
Please point out if I understand wrong, thank you！
meanface_indices, reverse_index1, reverse_index2, max_len = get_meanface(os.path.join(rootpath,'data', cfg.data_name, 'meanface.txt'), cfg.num_nb)

**Comment by jhb86253817** [comment]
Hi, I think the file 'meanface.txt' has been given for the datasets.
Are you using your own data? If so, you need to compute your own meanface, which is simply to record the average coordinates of the annotations in your training data.
And this file is related to the Neighbor Regression Module (NRM) mentined in the paper, not NMS for face detection.

**Comment by Forgeter0** [comment]
I think I know what to do next .thank you for you reply!

---Original---
From: "Haibo ***@***.***&gt;
Date: Wed, Dec 7, 2022 17:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jhb86253817/PIPNet] Excuse me,How to get the data for thisfile,'meanface.txt' (Issue #39)




 
Hi, I think the file 'meanface.txt' has been given for the datasets.
 Are you using your own data? If so, you need to compute your own meanface, which is simply to record the average coordinates of the annotations in your training data.
 And this file is related to the Neighbor Regression Module (NRM) mentined in the paper, not NMS for face detection.
