### ISSUE TITLE
Reproducing NME on test data

### ISSUE THREAD

**Issue by thomhert** [jhb86253817/PIPNet#4]
Hi
Thank you for sharing your codes.

I have downloaded one of the dataset (COFW) and tested using available pre-trained models (resnet18). The NME score that I got is 0.08758. If I multiply the score with 100%, it results in 8.758%.

Q: How to produce the same NME score as your paper? In the COFW, it is reported as 3.31%. Thank you.

**Comment by jhb86253817** [comment]
Hi, what's your PyTorch version? If it's over 1.6, there may be inconsistency for int tensor division, related to line 185 and 190 in functions.py. You can replace "max_ids/tmp_width" by "torch.floor(max_ids/tmp_width)"

**Comment by thomhert** [comment]
My PyTorch version is 1.7. I managed to get the same results by changing line 185 and 190 as you suggested. Thank you!
