### ISSUE TITLE
About LaPa preprocess.py part

### ISSUE THREAD

**Issue by AlptugCakici** [jhb86253817/PIPNet#41]
Hello, I was working on the LaPa dataset part of your landmark detection model. You shared the pretrained model of LaPa dataset but preprocess part is empty which is important for training. I know that preprocess is cropping the faces from dataset images and transforming them into 256x256 size. However, LaPa dataset does not contain face bounding coordinates unlike other datasets. How did you train your model without cropping images? Or did you manually select the face box coordinates?

**Comment by jhb86253817** [comment]
For Lapa, I cropped faces by first locating the minimum enclosing rectangle of the landmarks, then scale the rectangle by 1.2x for cropping.

**Comment by AlptugCakici** [comment]
Thanks for the information, i appreciate your hard work.
