### ISSUE TITLE
Where is celeba_bboxes.txt?

### ISSUE THREAD

**Issue by lrhweq** [jhb86253817/PIPNet#42]
I download all files from CelebA, but I do not find celeba_bboxes.txt. So I want to ask you where it is. Thank you very much.

**Comment by jhb86253817** [comment]
It's created by me. Please find it here: https://drive.google.com/drive/folders/1-5tIWQco_a6b-o-UJpr3dpGI5kwn_ROf

**Comment by lrhweq** [comment]
Thank you very much.
