### ISSUE TITLE
troubleshooting sh run_train.sh

### ISSUE THREAD

**Issue by apecundo** [jhb86253817/PIPNet#43]
Hi!

Thank you very much for this and making it public!

I have tried running the training for ResNet101 for 300W dataset (I am using Python on WSL with Ubuntu distro) and I have been getting this error.

"Traceback (most recent call last):
  File "lib/train.py", line 32, in <module>
    my_config = importlib.import_module(config_path, package = 'PIPNet')
  File "/home/apecundo725/anaconda3/envs/PIPNet/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 970, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'PIPNet.experiments.data_300W.pip_32_16_60_r101_l2_l1_10_1_nb10.'; 'PIPNet.experiments.data_300W.pip_32_16_60_r101_l2_l1_10_1_nb10' is not a package"

I have kept the folder structure as is from the github but I keep getting this error. I am wondering what fixes can be applied (I have tried adding __init__.py files but it does not help)

I have been able to run the preprocessing.py script but am stuck at the training part of the process. 

Thank you very much for the support.

**Comment by jhb86253817** [comment]
Hi, this is really strange as I just tried it on WSL, which seems fine. Let me know if you have other infomation for debugging.

**Comment by apecundo** [comment]
Hello! I applied the following fix that made my code run

![image](https://user-images.githubusercontent.com/63358780/218243052-7459a429-ccb5-4ee7-95db-fe139425769b.png)


For some reason, experiment_name variable gets an extra "." at the end which is why it would not run. 

I tried excluding the period by using [-4] instead of [-3]  when extracting the experiment name. 

Thanks!

**Comment by jhb86253817** [comment]
Great, good to know!
