### ISSUE TITLE
 some question when general the labels for train

### ISSUE THREAD

**Issue by mingliutju** [jhb86253817/PIPNet#7]
Hi, it is very nice work! I get some question when general the labels for train. In the paper, only one point in the score map is set 1, others are set 0, and one point in the offset map is set offset,others are set 0. In the inference phrase, how to promise all the score maps predicted are right? if there is one score map predicted is wrong, which could lead a wrong index for offset map in testing, the final landmark coordinate couldn't  be  right! why not set all possible offset in the gird?

**Comment by jhb86253817** [comment]
Hi, thanks for the question. Your suggestion is reasonable, and you may explore it if you're interested. For the current design, it also works fine because even if the classification is wrong, it usually falls at the neighboring area, and in that case, the offset part can still give correct predictions.

**Comment by mingliutju** [comment]
> Hi, thanks for the question. Your suggestion is reasonable, and you may explore it if you're interested. For the current design, it also works fine because even if the classification is wrong, it usually falls at the neighboring area, and in that case, the offset part can still give correct predictions.

Sorry, i test the final model (myself train), the result is not so good, even i use the predicted score map with the gt offset. when the score map predicted is wrong, the final result landmark is bad,because the integer part result is wrong , the correspond offset will be 0. maybe i should set all grid offset.

**Comment by mingliutju** [comment]
> Hi, thanks for the question. Your suggestion is reasonable, and you may explore it if you're interested. For the current design, it also works fine because even if the classification is wrong, it usually falls at the neighboring area, and in that case, the offset part can still give correct predictions.

Sorry, i test the final model (myself train), the result is not so good, even i use the predicted score map with the gt offset. when the score map predicted is wrong, the final result landmark is bad,because the integer part result is wrong , the correspond offset will be 0. maybe i should set all grid offset.
