### ISSUE TITLE
Problem about UDA training with curriculum

### ISSUE THREAD

**Issue by backkon** [jhb86253817/PIPNet#8]
when I tried to train with unlabeled data, I got results like this:
![image](https://user-images.githubusercontent.com/31430570/123499828-02664180-d66c-11eb-82b9-0ef59bb0d0c1.png)

I followed your guide in README.md and run 
`python lib/train_gssl.py experiments/data_300W_COFW_WFLW/pip_32_16_60_r18_l2_l1_10_1_nb10_wcc.py `

I  had no idea what the problem was.

**Comment by backkon** [comment]
After each iteration, the NME is almost constant, as shown in the figure above

**Comment by backkon** [comment]
[log.TXT](https://github.com/jhb86253817/PIPNet/files/6719476/log.TXT)
This is the output file.  Look forward to your reply.

**Comment by jhb86253817** [comment]
Hi, it seems to be the problem during inference, not training. I have modified line 223 and 228 of _functions_gssl.py_. You may try again.

**Comment by backkon** [comment]
Thanks a lot!
